### ISSUE TITLE
Actor的loss函数实现问题

### ISSUE THREAD

**Issue by Coastchb** [AIDefender/TSCAC#1]
请问一下，论文中公式(3)是把点击、点赞、关注等辅助任务作为离散行为，采用REIFORCE算法来更新参数吧？
但在代码里，采用的是DDPG算法（MULTICRI_DDPG类）？
请问这是出于什么考虑呢？

**Comment by AIDefender** [comment]
你好，实验中我们发现用确定性策略和DDPG算法会使训练更稳定。论文中的REINFORCE算法只是一个基础的框架，实际中TSCAC可以应用到各种RL算法中。

**Comment by Coastchb** [comment]
那请问你们是把点赞、关注等label处理为{0,1}的二元值吗？播放时长是[0,1]的连续值？

**Comment by AIDefender** [comment]
是的

**Comment by Coastchb** [comment]
> 

感谢回复。
还有一点有点疑惑：在main.py中，没看到behavior policy的预测值用于Actor的更新，看上去behavior policy和Actor/Critic是完全独立的。请问实际中没有采用importance sampling来进行offline correction么？

**Comment by AIDefender** [comment]
实际中用类似TD3+BC的方法，在RL loss的基础上加入了与数据集中(s,a)的模仿学习损失函数，作为offline correction。可以参考algos/DDPG.py的第89行。Behavior policy仅用于offline evaluation。
